---
title: "Graph Vocabulary in R"
output: html_notebook
---

Here is a cookbook with rapid recipes of elementary graph types. Use it for quick data visualization or when you are learning ggplot2 and R.


```{r, echo=FALSE} 
# initialize
# install.packages("ggplot2", "wordcloud", "RColorBrewer")
repository_directory <- "~/reps/r-graph-vocabulary/" # use your dir
setwd(repository_directory)

source("themes/theme_blank.R") # load blank theme

```

# Plain bar charts
```{r}
library(ggplot2)

df <- read.csv("data/3-columns.csv", sep=";") # read CSV in data.frame
names(df) <- c("col1", "col2", "col3") # column naming

x_seq <- seq(1:length(df$col2))   # we do not have x-data, so we generate a sequence
                                  # corresponding to amount of data
ggplot(df) +                      # define dataframe
  aes(x = x_seq, y = col2) +      # define x, y
  geom_bar(stat = "identity") +   # bars geometry, 'identity' force to use y-data
  theme_blank()                   # stylize: remove axis and labels

```

## Stacked bar charts

## Word cloud
```{r}
library(wordcloud)
library(RColorBrewer)

df <- read.csv("data/tags-freq.csv", sep=";") # read CSV in data.frame

colorPallete <- brewer.pal(n = 8, name = 'RdPu') # get Color Brewer pallete, [optional]
par(family = "Akrobat") # font family, [optional]

wordcloud(df$tag, df$freq,        # text chunks and their frequencies
          scale = c(3, 0.5),      # scale range
          min.freq = 50,          # min of m
          max.words = Inf,        # sample size
          colors = colorPallete,  # map colors
          random.order = FALSE,  
          random.color = FALSE,
          rot.per = .0,           # possible rotation, 0 to deny rotation
          ordered.colors = FALSE,
          use.r.layout = FALSE, 
          fixed.asp = TRUE)

```
## Beanplot

```{r}
library(beanplot)

data("singer", package = "lattice")

par(lend = 1, mai = c(0.8, 0.8, 0.5, 0.5))

beanplot(
    height ~ voice.part,
    data = singer,
    ll = 0.04,
    main = "beanplot",
    ylab = "body height (inch)",
    side = "both",
    border = NA,
    col = list("black", c("grey", "white"))
)
legend(
    "bottomleft",
    fill = c("black", "grey"),
    legend = c("Group 2", "Group 1")
)
```

## Treemaps

```{r}
library(treemapify)
library(viridis)

ggplot(G20, aes(area = gdp_mil_usd, 
                fill = hdi, 
                label = country,
                subgroup = region)) +
    geom_treemap() +
    geom_treemap_subgroup_border(col='white') +
    geom_treemap_subgroup_text(family = "Arial Black", 
                               place = "bottomleft", 
                               padding.x = grid::unit(1, "mm"),
                               padding.y = grid::unit(2, "mm"),
                               grow = FALSE, 
                               alpha = 0.25, 
                               colour = "black", 
                               min.size = 8) +
    geom_treemap_text(family = "Arial",
                      colour = "black",
                      place = "topleft",
                      padding.x = grid::unit(2, "mm"),
                      padding.y = grid::unit(2, "mm"),
                      reflow = T) +
    scale_fill_distiller(palette = "Spectral")
```

